language: julia

os:
  - linux
  - osx

julia:
  - 1.1
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - julia: nightly

notifications:
  email: false

after_success:
  - julia -e 'cd(Pkg.dir("PolynomialMatrices")); Pkg.add("Coverage"); using Coverage;
    Coveralls.submit(process_folder()); Codecov.submit(process_folder())'
